namespace: dev
replicaCount: 1

app:
  labels:
    app: myapp
  name: springapp
  image:
    repository: maheshgowdamg25/springboot
    tag: "latest"       # must be non-empty
    pullPolicy: Always
  port: 8080

  service:
    type: NodePort
       # must be in 30000-32767 if NodePort
